import csv
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from openpyxl import Workbook
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from sqlalchemy.orm import Session

from app.core.deps import require_permissions
from app.db.models import Alert, Incident, Report, SecurityLog
from app.db.session import get_db
from app.schemas.modules import ReportGenerateRequest

router = APIRouter()
REPORT_DIR = Path("generated_reports")


@router.get("")
def reports(_: object = Depends(require_permissions("reports:read")), db: Session = Depends(get_db)) -> dict:
    rows = db.query(Report).order_by(Report.created_at.desc()).all()
    return {"success": True, "data": [{"id": row.id, "name": row.name, "report_type": row.report_type, "format": row.format, "status": row.status, "path": row.path, "created_at": row.created_at} for row in rows]}


@router.post("/generate")
def generate(payload: ReportGenerateRequest, _: object = Depends(require_permissions("reports:create")), db: Session = Depends(get_db)) -> dict:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    safe_name = payload.name.lower().replace(" ", "_").replace("/", "_")
    extension = payload.format.lower()
    path = REPORT_DIR / f"{safe_name}.{extension}"
    summary = {
        "logs": db.query(SecurityLog).count(),
        "alerts": db.query(Alert).count(),
        "incidents": db.query(Incident).count(),
    }
    if extension == "pdf":
        pdf = canvas.Canvas(str(path), pagesize=letter)
        pdf.setFont("Helvetica-Bold", 18)
        pdf.drawString(72, 740, payload.name)
        pdf.setFont("Helvetica", 11)
        pdf.drawString(72, 710, f"Report type: {payload.report_type}")
        pdf.drawString(72, 690, f"Total logs: {summary['logs']}")
        pdf.drawString(72, 672, f"Total alerts: {summary['alerts']}")
        pdf.drawString(72, 654, f"Total incidents: {summary['incidents']}")
        pdf.drawString(72, 620, "Generated by CyberShield XDR report service.")
        pdf.save()
    elif extension in {"xlsx", "excel"}:
        path = path.with_suffix(".xlsx")
        wb = Workbook()
        ws = wb.active
        ws.title = "SOC Summary"
        ws.append(["Metric", "Value"])
        for key, value in summary.items():
            ws.append([key.title(), value])
        wb.save(path)
        extension = "xlsx"
    elif extension == "csv":
        with path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.writer(handle)
            writer.writerow(["Metric", "Value"])
            writer.writerows((key.title(), value) for key, value in summary.items())
    else:
        raise HTTPException(status_code=400, detail="Supported formats: pdf, xlsx, csv")
    row = Report(name=payload.name, report_type=payload.report_type, format=extension, status="ready", path=str(path))
    db.add(row)
    db.commit()
    db.refresh(row)
    return {"success": True, "data": {"id": row.id, "name": row.name, "format": row.format, "status": row.status, "download_url": f"/api/v1/reports/{row.id}/download"}}


@router.get("/{report_id}/download")
def download(report_id: int, _: object = Depends(require_permissions("reports:export")), db: Session = Depends(get_db)) -> FileResponse:
    report = db.get(Report, report_id)
    if not report or not report.path or not Path(report.path).exists():
        raise HTTPException(status_code=404, detail="Report file not found")
    return FileResponse(report.path, filename=Path(report.path).name)
